version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: api_mgmt_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: apipass
      POSTGRES_DB: apidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: api_mgmt_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: